@testable import HailDaemonKit

/// The table for `SanitizeTests`: one row per attack class from #44 and the threat model's B3 rows.
extension SanitizeTests {
    /// Builds a string from a scalar Swift will not accept as a literal (noncharacters).
    static func scalar(_ value: UInt32) -> String {
        Unicode.Scalar(value).map { String($0) } ?? ""
    }

    static func invisible(_ name: String, _ input: String) -> Row {
        Row(name: name, input: input, expect: .failure(.hiddenCharacters("invisible format character")))
    }

    static func bidi(_ name: String, _ input: String) -> Row {
        Row(name: name, input: input, expect: .failure(.hiddenCharacters("bidirectional control")))
    }

    static func passes(_ name: String, _ input: String) -> Row {
        Row(name: name, input: input, expect: .success([input]))
    }

    static let rows: [Row] = [
        passes("plain text passes", "echo hi"),
        Row(name: "shell metacharacters are not sanitization's job (#41 guards)",
            input: #"; rm -rf / && echo "$(x)" `y` | z"#,
            expect: .success([#"; rm -rf / && echo "$(x)" `y` | z"#])),
        Row(name: "tab is stripped, it is the completion key at a target", input: "rm -rf /tmp/x\t",
            expect: .success(["rm -rf /tmp/x"])),
        Row(name: "NFC maps lookalikes to shell metacharacters; guards must run on the output",
            input: "echo hi\u{037E} rm -rf x and \u{1FEF}id\u{1FEF}", expect: .success(["echo hi; rm -rf x and `id`"])),
        Row(name: "NFC normalises a decomposed sequence", input: "cafe\u{0301}", expect: .success(["café"])),
        Row(name: "SGR colour escapes stripped", input: "\u{1B}[31mred\u{1B}[0m text",
            expect: .success(["red text"])),
        Row(name: "cursor movement CSI stripped", input: "a\u{1B}[2J\u{1B}[H\u{1B}[?25lb",
            expect: .success(["ab"])),
        Row(name: "C1 CSI stripped", input: "a\u{9B}31mb", expect: .success(["ab"])),
        Row(name: "OSC title with BEL stripped", input: "\u{1B}]0;title\u{07}ok", expect: .success(["ok"])),
        Row(name: "OSC with ST stripped", input: "\u{1B}]8;;http://x\u{1B}\\link\u{1B}]8;;\u{1B}\\",
            expect: .success(["link"])),
        Row(name: "charset and cursor ESC escapes stripped", input: "\u{1B}(Bx\u{1B}7y\u{1B}8",
            expect: .success(["xy"])),
        Row(name: "trailing lone ESC stripped", input: "x\u{1B}", expect: .success(["x"])),
        Row(name: "C0, DEL and C1 stripped", input: "a\u{00}\u{01}\u{07}\u{1F}\u{7F}\u{80}\u{99}b",
            expect: .success(["ab"])),
        Row(name: "embedded newline rejected by default", input: "rm -rf x\necho y",
            expect: .failure(.containsLineBreak)),
        Row(name: "carriage return rejected by default", input: "a\rb", expect: .failure(.containsLineBreak)),
        Row(name: "newline hidden inside a CSI still rejected", input: "a\u{1B}[\nmb",
            expect: .failure(.containsLineBreak)),
        Row(name: "newline hidden inside an unterminated OSC still rejected", input: "a\u{1B}]0;x\nrm",
            expect: .failure(.containsLineBreak)),
        Row(name: "leading newline rejected", input: "\none", expect: .failure(.containsLineBreak)),
        Row(name: "split policy yields lines, blank ones dropped", input: "one\r\n\n  \ntwo\n",
            expect: .success(["one", "two"]), policy: SanitizePolicy(newlines: .split)),
        Row(name: "trailing newline alone is not a second command", input: "one\n", expect: .success(["one"])),
        Row(name: "bidi override rejected", input: "safe\u{202E}rm",
            expect: .failure(.hiddenCharacters("bidirectional control"))),
        Row(name: "bidi isolate rejected", input: "\u{2066}x\u{2069}",
            expect: .failure(.hiddenCharacters("bidirectional control"))),
        Row(name: "zero-width joiner between letters rejected", input: "r\u{200D}m",
            expect: .failure(.hiddenCharacters("zero-width character"))),
        Row(name: "zero-width joiner inside an emoji sequence allowed", input: "👨‍👩‍👧 and ❤️‍🔥",
            expect: .success(["👨‍👩‍👧 and ❤️‍🔥"])),
        Row(name: "zero-width space rejected", input: "a\u{200B}b",
            expect: .failure(.hiddenCharacters("zero-width character"))),
        Row(name: "BOM rejected", input: "\u{FEFF}x", expect: .failure(.hiddenCharacters("zero-width character"))),
        Row(name: "word joiner rejected", input: "a\u{2060}b",
            expect: .failure(.hiddenCharacters("zero-width character"))),
        bidi("left-to-right mark rejected", "r\u{200E}m"),
        bidi("right-to-left mark rejected", "r\u{200F}m"),
        bidi("arabic letter mark rejected", "r\u{061C}m"),
        invisible("soft hyphen rejected", "r\u{00AD}m"),
        invisible("invisible times rejected", "r\u{2062}m"),
        invisible("tag character between letters rejected", "r\u{E0072}m"),
        invisible("combining grapheme joiner rejected", "r\u{034F}m"),
        invisible("variation selector between letters rejected", "r\u{FE0F}m -rf /"),
        invisible("interlinear annotation anchor rejected", "a\u{FFF9}b"),
        passes("emoji presentation selector and keycap allowed", "❤️ 1️⃣ ☺️"),
        passes("emoji flag tag sequence allowed", "🏴󠁧󠁢󠁳󠁣󠁴󠁿"),
        invisible("tags after a non-flag emoji rejected", "echo hi 🔥\u{E0072}\u{E0075}\u{E006E}\u{E007F}"),
        invisible("unterminated tag run after the flag rejected", "🏴\u{E0067}\u{E0062}\u{E0073}"),
        invisible("tags after a completed flag rejected", "🏴󠁧󠁢󠁳󠁣󠁴󠁿\u{E0061}\u{E007F}"),
        invisible("well-formed but unregistered subdivision tag run rejected",
                  "🏴\u{E0061}\u{E0061}\u{E0061}\u{E007F}"),
        passes("the other two registered subdivision flags allowed",
               "🏴󠁧󠁢󠁥󠁮󠁧󠁿🏴󠁧󠁢󠁷󠁬󠁳󠁿"),
        invisible("six-letter unregistered tag run rejected",
                  "🏴\u{E0069}\u{E0067}\u{E006E}\u{E006F}\u{E0072}\u{E0065}\u{E007F}"),
        passes("registered flag followed by text allowed", "🏴󠁧󠁢󠁥󠁮󠁧󠁿 flag then text"),
        Row(name: "no-break and ideographic spaces fold to a plain space",
            input: "rm\u{00A0}-rf\u{3000}/x\u{2009}y", expect: .success(["rm -rf /x y"])),
        Row(name: "braille blank rejected", input: "rm\u{2800}-rf",
            expect: .failure(.hiddenCharacters("blank lookalike character"))),
        Row(name: "noncharacter rejected", input: "r" + scalar(0xFFFF) + "m",
            expect: .failure(.hiddenCharacters("noncharacter"))),
        Row(name: "noncharacter in the FDD0 block rejected", input: "r" + scalar(0xFDD5) + "m",
            expect: .failure(.hiddenCharacters("noncharacter"))),
        Row(name: "split policy caps the number of lines", input: String(repeating: "a\n", count: 21),
            expect: .failure(.tooManyLines(lines: 21, limit: 20)), policy: SanitizePolicy(newlines: .split)),
        Row(name: "split policy delivers up to the line cap", input: String(repeating: "a\n", count: 20),
            expect: .success(Array(repeating: "a", count: 20)), policy: SanitizePolicy(newlines: .split)),
        invisible("over-long tag run rejected",
                  "🏴\u{E0061}\u{E0061}\u{E0061}\u{E0061}\u{E0061}\u{E0061}\u{E0061}\u{E007F}"),
        invisible("mongolian free variation selector rejected", "r\u{180B}m"),
        invisible("hangul filler rejected", "r\u{3164}m"),
        invisible("khmer inherent vowel rejected", "r\u{17B4}m"),
        invisible("text variation selector other than the emoji pair rejected", "chmod 7\u{FE00}77"),
        invisible("ideographic variation selector rejected", "1\u{E0100}"),
        invisible("emoji selector after a digit without the keycap rejected", "chmod 7\u{FE0F}77"),
        invisible("emoji selector after an asterisk without the keycap rejected", "rm -rf *\u{FE0F}"),
        Row(name: "zero-width joiner to a text-presentation symbol rejected", input: "🔥\u{200D}™",
            expect: .failure(.hiddenCharacters("zero-width character"))),
        passes("zero-width joiner to a symbol that carries the emoji selector allowed", "🏳️‍⚧️"),
        passes("skin tone modifier allowed", "👍🏽"),
        Row(name: "DCS payload stripped with its introducer", input: "a\u{1B}Pq rm\u{1B}\\b",
            expect: .success(["ab"])),
        Row(name: "APC and PM strings stripped", input: "a\u{1B}_x\u{07}\u{1B}^y\u{9C}b",
            expect: .success(["ab"])),
        Row(name: "C1 DCS stripped", input: "a\u{90}q rm\u{9C}b", expect: .success(["ab"])),
        Row(name: "newline inside an unterminated DCS still rejected", input: "a\u{1B}Px\nrm",
            expect: .failure(.containsLineBreak)),
        Row(name: "vertical tab and form feed stripped", input: "a\u{0B}b\u{0C}c", expect: .success(["abc"])),
        Row(name: "next line control stripped", input: "a\u{85}b", expect: .success(["ab"])),
        Row(name: "line separator rejected by default", input: "a\u{2028}b",
            expect: .failure(.containsLineBreak)),
        Row(name: "paragraph separator splits under the split policy", input: "a\u{2029}b",
            expect: .success(["a", "b"]), policy: SanitizePolicy(newlines: .split)),
        Row(name: "combining marks cannot inflate the character cap past the byte cap",
            input: String(repeating: "x" + String(repeating: "\u{0301}", count: 50), count: 200),
            expect: .failure(.tooManyBytes(bytes: 20_200, limit: 8_192))),
        Row(name: "byte cap is re-checked after NFC expands the text",
            input: "a" + String(repeating: "\u{0F73}", count: 2_730),
            expect: .failure(.tooManyBytes(bytes: 16_381, limit: 8_192))),
        Row(name: "empty rejected", input: "", expect: .failure(.empty)),
        Row(name: "whitespace only rejected", input: " \t ", expect: .failure(.empty)),
        Row(name: "only escapes rejected as empty", input: "\u{1B}[0m", expect: .failure(.empty)),
        Row(name: "2,000 characters pass", input: String(repeating: "x", count: 2_000),
            expect: .success([String(repeating: "x", count: 2_000)])),
        Row(name: "2,001 characters rejected", input: String(repeating: "x", count: 2_001),
            expect: .failure(.tooLong(characters: 2_001, limit: 2_000))),
        Row(name: "a megabyte rejected before any other work",
            input: String(repeating: "\u{202E}", count: 1_048_576),
            expect: .failure(.tooManyBytes(bytes: 3_145_728, limit: 8_192)))
    ]
}
